export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";

export const GET_MY_BOOKINGS_SUCCESS = "GET_MY_BOOKINGS_SUCCESS";
export const GET_INCOMING_BOOKINGS_SUCCESS = "GET_INCOMING_BOOKINGS_SUCCESS";
export const BOOKING_ERROR = "BOOKING_ERROR";
